package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

//this file works
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ChoiceBox;

public class memberRetryController {
	@FXML
	private TextField registerEmail;
	@FXML
	private TextField registerName;
	@FXML
	private Button RegisterSubmit;
	@FXML
	private TextField registerContact;
	@FXML
	private TextField registerPassword;
	@FXML
	private ChoiceBox registerWeeks;
	@FXML
	private ChoiceBox registerEquipmentChoice;
	@FXML
	private Button registerEquipmentSubmit;
	@FXML
	private TextField registerEquipmentQuantity;
	@FXML
	private ChoiceBox registerBundleChoice;
	@FXML
	private Button registerBundleSubmit;
	@FXML
	private TextField registerBundleQuantity;
	@FXML
	private Button registerGuideToggleY;
	@FXML
	private Button registerGuideToggleN;
	@FXML
	private Button registerHotelToggleY;
	@FXML
	private Button registerHotelToggleN;
	@FXML
	private TextField updateName;
	@FXML
	private Button updateSubmit;
	@FXML
	private TextField updateContact;
	@FXML
	private TextField updatePassword;
	@FXML
	private ChoiceBox updateWeeks;
	@FXML
	private ChoiceBox updateEquipmentChoice;
	@FXML
	private Button updateEquipmentSubmit;
	@FXML
	private TextField updateEquipmentQuantity;
	@FXML
	private ChoiceBox updateBundleChoice;
	@FXML
	private Button updateBundleSubmit;
	@FXML
	private TextField updateBundleQuantity;
	@FXML
	private TextField updateEmail;
	@FXML
	private Button updateGuideToggleN;
	@FXML
	private Button updateGuideToggleY;
	@FXML
	private Button updateHotelToggleY;
	@FXML
	private Button updateHotelToggleN;
	@FXML
	private Button deleteSubmit;
	@FXML
	private TextField deleteEmail;

	// Event Listener on Button[#RegisterSubmit].onAction
	@FXML
	public void RegisterMemberRegisterSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerEquipmentSubmit].onAction
	@FXML
	public void RegisterMemberEquipmentSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerBundleSubmit].onAction
	@FXML
	public void RegisterMemberBundleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerGuideToggleY].onAction
	@FXML
	public void registerGuideYes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerGuideToggleN].onAction
	@FXML
	public void registerGuideNo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerHotelToggleY].onAction
	@FXML
	public void registerHotelYes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerHotelToggleN].onAction
	@FXML
	public void registerHotelNo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateSubmit].onAction
	@FXML
	public void updateMemberSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateEquipmentSubmit].onAction
	@FXML
	public void UpdateMemberEquipmentSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateBundleSubmit].onAction
	@FXML
	public void UpdateMemberBundleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateGuideToggleN].onAction
	@FXML
	public void updateGuideNo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateGuideToggleY].onAction
	@FXML
	public void updateGuideYes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateHotelToggleY].onAction
	@FXML
	public void updateHotelYes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateHotelToggleN].onAction
	@FXML
	public void updateHotelNo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteSubmit].onAction
	@FXML
	public void deleteSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
}
