package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Spinner;

import javafx.scene.control.ChoiceBox;

public class memberPageController {
	@FXML
	private TextField registerEmail;
	@FXML
	private TextField registerName;
	@FXML
	private Button RegisterSubmit;
	@FXML
	private TextField registerContact;
	@FXML
	private TextField registerPassword;
	@FXML
	private ChoiceBox registerWeeks;
	@FXML
	private Spinner registerEquipmentQuantity;
	@FXML
	private ChoiceBox registerEquipmentChoice;
	@FXML
	private Button registerEquipmentSubmit;
	@FXML
	private Spinner registerBundleQuantity;
	@FXML
	private ChoiceBox registerBundleChoice;
	@FXML
	private Button registerBundleSubmit;
	@FXML
	private Button registerHotelToggle;
	@FXML
	private Button registerGuideToggle;
	@FXML
	private TextField updateName;
	@FXML
	private Button updateSubmit;
	@FXML
	private TextField updateContact;
	@FXML
	private TextField updatePassword;
	@FXML
	private ChoiceBox updateWeeks;
	@FXML
	private Spinner updateEquipmentQuantity;
	@FXML
	private ChoiceBox updateEquipmentChoice;
	@FXML
	private Button updateEquipmentSubmit;
	@FXML
	private Spinner updateBundleQuantity;
	@FXML
	private ChoiceBox updateBundleChoice;
	@FXML
	private Button updateBundleSubmit;
	@FXML
	private TextField updateEmail;
	@FXML
	private Button updateGuideToggle;
	@FXML
	private Button updateHotelToggle;
	@FXML
	private Button deleteSubmit;
	@FXML
	private TextField deleteEmail;

	// Event Listener on Button[#RegisterSubmit].onAction
	@FXML
	public void RegisterMemberRegisterSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerEquipmentSubmit].onAction
	@FXML
	public void RegisterMemberEquipmentSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#registerBundleSubmit].onAction
	@FXML
	public void RegisterMemberBundleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateSubmit].onAction
	@FXML
	public void updateMemberSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateEquipmentSubmit].onAction
	@FXML
	public void UpdateMemberEquipmentSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateBundleSubmit].onAction
	@FXML
	public void UpdateMemberBundleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteSubmit].onAction
	@FXML
	public void deleteSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
}
