package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import static ca.mcgill.ecse.climbsafe.javafx.fxml.controllers.ViewUtils.successful;
import ca.mcgill.ecse.climbsafe.javafx.fxml.ClimbsafeFxmlView;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet2Controller; 
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet1Controller; 

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Spinner;

import javafx.scene.control.ChoiceBox;

public class memberPageController {
	@FXML
	private TextField rmEmail1;
	@FXML
	private TextField rmName1;
	@FXML
	private ChoiceBox rmHotel1;
	@FXML
	private ChoiceBox rmWantGuide1;
	@FXML
	private ChoiceBox rmWantHotel1;
	@FXML
	private Button rmSubmit1;
	@FXML
	private TextField rmContact1;
	@FXML
	private TextField rmPassword1;
	@FXML
	private ChoiceBox rmWeeks1;
	@FXML
	private Spinner rmEquipmentQuantity1;
	@FXML
	private ChoiceBox rmEquipment1;
	@FXML
	private Button rmEquipmentSubmit1;
	@FXML
	private Spinner rmBundleQuantity1;
	@FXML
	private ChoiceBox rmBudle1;
	@FXML
	private Button rmBundleSubmit1;
	@FXML
	private ChoiceBox rmGuide1;
	@FXML
	private TextField upName;
	@FXML
	private ChoiceBox upHotel;
	@FXML
	private ChoiceBox upWantGuide;
	@FXML
	private ChoiceBox upWantHotel;
	@FXML
	private Button upSubmit;
	@FXML
	private TextField upContact;
	@FXML
	private TextField upPassword;
	@FXML
	private ChoiceBox upWeeks;
	@FXML
	private Spinner upEquipmentQuantity;
	@FXML
	private ChoiceBox upEquipment;
	@FXML
	private Button upEquipmentSubbmit;
	@FXML
	private Spinner upBundleQuantity;
	@FXML
	private ChoiceBox upBudle;
	@FXML
	private Button upBundleSubmit;
	@FXML
	private ChoiceBox upGuide;
	@FXML
	private TextField upEmail;
	@FXML
	private Button deleteSend;
	@FXML
	private TextField deleteEmail;

	// Event Listener on Button[#rmSubmit1].onAction
	@FXML
	public void RegisterMemberRegisterSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#rmEquipmentSubmit1].onAction
	@FXML
	public void RegisterMemberEquipmentSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#rmBundleSubmit1].onAction
	@FXML
	public void RegisterMemberBundleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#upSubmit].onAction
	@FXML
	public void UpdateMemberSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#upEquipmentSubbmit].onAction
	@FXML
	public void UpdateMemberEquipmentSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#upBundleSubmit].onAction
	@FXML
	public void UpdateMemberBundleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteSend].onAction
	@FXML
	public void deleteSubmit(ActionEvent event) {
		// TODO Autogenerated
	    String email = deleteEmail.getText();
	    if (email == null || email.trim().isEmpty()) {
	      ViewUtils.showError("Please input a valid email");
	    }
	      else {
	  
	      if (successful(() -> ClimbSafeFeatureSet1Controller.deleteMember(email))) {
	    	  deleteEmail.setText("");
	        ClimbsafeFxmlView.getInstance().refresh();
	      }
	      }
		
	}
}
