package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;
import ca.mcgill.ecse.climbsafe.controller.TOAssignment;

import javafx.scene.control.Button;
import javafx.scene.control.TableCell;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.paint.Color;
import javafx.beans.binding.Bindings;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class viewAssignmentPageController {
	@FXML
	private TableView<TOAssignment> overviewTable;
	@FXML
	private TextField emailTextField;
	@FXML
	private TextField codeTextField;
	@FXML
	private Button startButton;
	@FXML
	private Button finishButton;
	@FXML
	private Button CancelButton;
	@FXML
	private TextField weekTextField;
	@FXML
	private Button payButton;
	@FXML
	private Button initiateButton;
	
	
	// Event Listener on Button[#startButton].onAction
	@FXML
	public void startClicked(ActionEvent event) {
		
	}
	// Event Listener on Button[#finishButton].onAction
	@FXML
	public void finishClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#CancelButton].onAction
	@FXML
	public void cancelClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#payButton].onAction
	@FXML
	public void payClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#initiateButton].onAction
	@FXML
	public void initiateClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
